# Generated by Django 4.2.8 on 2024-09-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(help_text='The name of the project.', max_length=70)),
                ('starting_date', models.DateField(verbose_name='Date the project was started.')),
                ('P_ID', models.CharField(max_length=20, verbose_name='ID number of the project.')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(help_text='The name of the task.', max_length=50)),
                ('starting', models.DateField(verbose_name='Date the task was started.')),
                ('email', models.EmailField(help_text='The contact email for the representative.', max_length=254)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='projectp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_set', to='projectp.project')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.task')),
            ],
        ),
    ]
